In [904]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [905]:
df = pd.read_csv('01_logit classification.csv')

In [906]:
df.sample(5)

      User ID  Gender  Age  EstimatedSalary  Purchased
170  15587013    Male   21            88000          0
394  15757632  Female   39            59000          0
387  15627220    Male   39            71000          0
238  15617877  Female   46            82000          0
97   15582492    Male   28           123000          1

In [907]:
X = df.iloc[:,[2,3]].values
y = df.iloc[:,-1].values

In [908]:
df.shape

(400, 5)

In [909]:
from sklearn.model_selection import train_test_split
X_train, X_test  ,y_train, y_test = train_test_split(X,y, test_size=0.20,random_state=0)

In [910]:
X_test.shape

(80, 2)

In [911]:
X_train.shape

(320, 2)

# scaled the data 
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
sc

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [912]:
# model train 
from sklearn.linear_model import LogisticRegression
classifire = LogisticRegression()
classifire

LogisticRegression()

In [913]:
classifire.fit(X_train,y_train)

LogisticRegression()

In [914]:
y_pred = classifire.predict(X_test)

In [915]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [916]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [917]:
af = pd.DataFrame({'actual':y_test , 'pred':y_pred})

In [918]:
af.head()

   actual  pred
0       0     0
1       0     0
2       0     0
3       0     0
4       0     0

In [919]:
# model accuracy
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test,y_pred)
print(ac*100)

91.25

In [920]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[56  2]
 [ 5 17]]

In [921]:
# digonal sum / sum of all element 
accuracy = (57+17) / (57+1+5+17)
print(accuracy*100)

92.5

In [922]:
# This is to get the Classification Report
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.92      0.97      0.94        58
           1       0.89      0.77      0.83        22

    accuracy                           0.91        80
   macro avg       0.91      0.87      0.89        80
weighted avg       0.91      0.91      0.91        80

In [923]:
bias = classifire.score(X_train, y_train)
print("bias",bias)

variance = classifire.score(X_test, y_test)
print("variance",variance)

bias 0.81875
variance 0.9125

In [924]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

Accuracy: 0.9125
Precision: 0.8947368421052632
Recall: 0.7727272727272727
F1 Score: 0.8292682926829268

In [925]:
from sklearn.svm import SVC
svc = SVC()
svc

SVC()

In [926]:
svc.fit(X_train,y_train)

SVC()

In [927]:
y_pred2 = svc.predict(X_test)

In [928]:
y_pred2

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [929]:
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))

0.825
[[56  2]
 [12 10]]

In [930]:
bias = svc.score(X_train,y_train)
bias

0.7625

In [931]:
var = svc.score(X_test,y_test)
var

0.825

In [932]:
cr1 = classification_report(y_test,y_pred2)
print(cr1)

              precision    recall  f1-score   support

           0       0.82      0.97      0.89        58
           1       0.83      0.45      0.59        22

    accuracy                           0.82        80
   macro avg       0.83      0.71      0.74        80
weighted avg       0.83      0.82      0.81        80

In [933]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()
kn.fit(X_train,y_train)

KNeighborsClassifier()

In [934]:
y_pred3 = kn.predict(X_test)

In [935]:
y_pred3

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [936]:
print(accuracy_score(y_test,y_pred3))

0.8375

In [937]:
bias = kn.score(X_train,y_train)
bias

0.871875

In [938]:
var = kn.score(X_test,y_test)
var

0.8375

In [939]:
cr1 = classification_report(y_test,y_pred3)
print(cr1)

              precision    recall  f1-score   support

           0       0.88      0.90      0.89        58
           1       0.71      0.68      0.70        22

    accuracy                           0.84        80
   macro avg       0.80      0.79      0.79        80
weighted avg       0.84      0.84      0.84        80

In [940]:
from sklearn.naive_bayes import MultinomialNB
ga = MultinomialNB()
ga

MultinomialNB()

In [941]:
ga.fit(X_train,y_train)

MultinomialNB()

In [942]:
y_pred4 = ga.predict(X_test)

In [943]:
y_pred4

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [944]:
print(accuracy_score(y_test,y_pred4))

0.5625

In [945]:
b = ga.score(X_train,y_train)
b

0.671875

In [946]:
v = ga.score(X_test,y_test)
v

0.5625

In [966]:


from sklearn.ensemble import RandomForestClassifier

dc = RandomForestClassifier(max_depth=5,n_estimators=30,criterion='entropy',random_state=0)

dc.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=5, n_estimators=30,
                       random_state=0)

In [967]:
y_pred_de = dc.predict(X_test)

In [968]:
print(accuracy_score(y_test,y_pred_de))

0.95

In [950]:
b = dc.score(X_train,y_train)
b

0.9125

In [951]:
v = dc.score(X_test,y_test)
v

0.9375

In [952]:
# 91

In [953]:
s.p

NameError: name 's' is not defined

In [ ]:
print("LR",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print("SVM",accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print("KNN",accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))

LR 0.925
[[58  0]
 [ 6 16]]
SVM 0.95
[[55  3]
 [ 1 21]]
KNN 0.95
[[55  3]
 [ 1 21]]

# Future Prediction

In [ ]:
dataset1 = pd.read_csv("01_final1.csv")
d2 = dataset1.copy()

In [ ]:
d2

   Unnamed: 0   User ID  Gender  Age  EstimatedSalary
0           0  15724611    Male   45            60000
1           1  15725621  Female   79            64000
2           2  15725622    Male   23            78000
3           3  15720611  Female   34            45000
4           4  15588044    Male   29            76000
5           5  15746039  Female   70            89000
6           6  15704887    Male   86           120000
7           7  15746009  Female   46            23000
8           8  15876009    Male   32            70000
9           9  15886009  Female  100            90000

In [ ]:
dataset1 = dataset1. iloc[:, [3, 4]].values

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
M = sc.fit_transform(dataset1)

In [ ]:
y_pred1= pd.DataFrame()

In [ ]:
d2['y_pred1'] = classifire.predict(M)

In [ ]:
# d2.to_csv("final2.csv")

In [ ]:
# d2